### ISSUE TITLE
Remove Metis from repo ?

### ISSUE THREAD

**Issue by pecchia** [libnegf/libnegf#5]
Connected to Balint's issue, I think we should remove Metis-4.0, as it is not even used. In case we will decide we need it we can set an automatic download.

**Comment by gpenazzi** [comment]
+1. 
Related, there are some unused source files (`src/iterative.F90` de facto superseded by `iterative_dns.F90`, `src/unused` and maybe some more?). We should eliminate those as well, they'll be anyway preserved in the git history.
