### ISSUE TITLE
Release 1.1.0 is broken: it doesn't install any headers

### ISSUE THREAD

**Issue by yurivict** [libnegf/libnegf#62]

**Comment by yurivict** [comment]
@pecchia Both 1.1.0 and 1.1.1 are broken - they don't install headers.

**Comment by pecchia** [comment]
Thanks for this comment. This is partially true. In config.cmake it is possible to set  INSTALL_INCLUDE_DIR and INSTALL_MOD_DIR, currently set to "libnegf" and "libnegf/modfiles". The default installation folder is in /usr/local. 
  
For installation in a user floder it is possible, for instance, to define
set(CMAKE_INSTALL_PREFIX "/home/username/libnegf1.1")
 
Then after make & make install, I find under that folder the "lib" and "include" subfolders with C headers and fortran modules.  
 
But I agree that things could be improved. Probably it is better to set as default:
set(INSTALL_INCLUDE_DIR "" ...)
set(INSTALL_MOD_DIR "modfiles" ...)

Please give other suggestions as I am not a sofware engineer and probably I always overlooked the user-side experience.

**Comment by yurivict** [comment]
1.1.2 works, thanks!
